---
  - name: config web VMs with docker
    hosts: webservers
    become: true
    tasks:

    - name: Install docker.io and update cache
      apt:
        name: docker.io
        update_cache: yes
        state: present

    - name: install python3-pip
      apt:
        name: python3-pip
        state: present

    - name: use pip module to install docker
      pip:
        name: docker
        state: present

    - name: use docker-container module to install the cyberxsecurity/dvwa container and publish port 80 on container to port 80 on host
      docker_container:
        name: dvwa
        image: cyberxsecurity/dvwa
        state: started
        restart_policy: always
        published_ports: 80:80

    - name: Enable docker service
      systemd:
        name: docker
        enabled: yes
